import type { Metadata } from "next";
import "./globals.css";
import { Providers as ThemeProviders } from "./providers";
import { inter } from "./fonts";


export const metadata: Metadata = {
  title: {
    default: "Finance App",
    template: "%s | Finance App",
  },
  description: "Generated by create next app",
  icons: {
    icon: '/icons/finance-app-icon.svg',
    apple: '/icons/finance-app-icon.svg',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      
        <body suppressHydrationWarning
          className={`${inter.className} antialiased min-h-screen flex flex-col px-8`}
        >
          <ThemeProviders>
            {children}
          </ThemeProviders>
        </body>
    </html>
  );
}
