import type { Metadata } from "next";
import "./globals.css";
import { Providers as ThemeProviders } from "./providers";
import { inter } from "./fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      
        <body
          className={`${inter.className} antialiased`}
        >
          <ThemeProviders>
            {children}
          </ThemeProviders>
        </body>
    </html>
  );
}
